'use strict';

// tract pull — pull all tract repos found under ~/.tract/
//
// Discovers all git repos directly under ~/.tract/ and pulls each one.
// Also symlinks builtin skills into standard locations and generates a
// personalised tract-workspace skill with a workspace.md resource.

const fs   = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const { execSync, spawnSync } = require('child_process');
const chalk = require('chalk');

const TRACT_DIR      = path.join(process.env.HOME, '.tract');
const BUILTIN_SKILLS = path.join(__dirname, '..', '..', '.tract', 'skills');
const WORKSPACE_YAML = path.join(TRACT_DIR, 'workspace.yaml');
const SKILL_TARGETS  = [
  path.join(process.env.HOME, '.claude', 'skills'),
  path.join(process.env.HOME, '.copilot', 'skills'),
];

// Read ~/.tract/workspace.yaml — the canonical workspace config.
// Returns { projects: [{ prefix, name, path, src? }], workspace: { name? } }
function readWorkspace() {
  try {
    if (fs.existsSync(WORKSPACE_YAML))
      return yaml.load(fs.readFileSync(WORKSPACE_YAML, 'utf8')) || {};
  } catch { /* ignore */ }
  return {};
}

// Symlink each builtin skill into standard global skill directories.
function linkSkills() {
  if (!fs.existsSync(BUILTIN_SKILLS)) return;
  const skillNames = fs.readdirSync(BUILTIN_SKILLS)
    .filter(n => fs.statSync(path.join(BUILTIN_SKILLS, n)).isDirectory());

  let linked = 0;
  for (const target of SKILL_TARGETS) {
    try {
      fs.mkdirSync(target, { recursive: true });
      for (const name of skillNames) {
        const src  = path.join(BUILTIN_SKILLS, name);
        const dest = path.join(target, name);
        if (!fs.existsSync(dest)) {
          fs.symlinkSync(src, dest);
          linked++;
        }
      }
    } catch { /* non-fatal */ }
  }
  if (linked > 0)
    console.log(chalk.gray(`  (linked ${linked} skill(s) into ~/.claude/skills and ~/.copilot/skills)`));
}

// Generate the personalised tract-workspace skill, written fresh on every pull.
function writeWorkspaceSkill(repos) {
  const ws       = readWorkspace();
  const projects = ws.projects || [];

  // Build a lookup from prefix -> project entry (for src: field)
  const byPrefix = {};
  for (const p of projects) {
    if (p.prefix) byPrefix[p.prefix.toUpperCase()] = p;
  }

  const repoLines = repos.length === 0
    ? '_No repos cloned yet. Run `tract clone <url>` to get started._'
    : repos.map(({ name, dir }) => {
        const proj = byPrefix[name.toUpperCase()] || {};
        const srcLine = proj.src ? `\n  - Source code: \`${proj.src}\`` : '';
        return `- **${name}**: \`${dir}\`${srcLine}`;
      }).join('\n');

  const hasSrc = projects.some(p => p.src);
  const hintSection = hasSrc ? '' :
    '\n_To add source code locations, add a `src:` field to each project in ' +
    '`~/.tract/workspace.yaml`._\n';

  const skillMd = `---
name: tract-workspace
description: This developer's tract workspace — which ticket repos are cloned, where they live, and where source code is. Always load this skill when working with tract tickets or any of the listed projects.
---

See \`workspace.md\` for the current workspace state.
`;

  const workspaceMd = `# Tract Workspace

This file is auto-generated by \`tract pull\`. Do not edit by hand.
Last updated: ${new Date().toISOString()}

## Ticket Repositories

${repoLines}
${hintSection}
## Workflow

Run \`tract pull\` at the start of each session to sync all repos and refresh this file.
`;

  for (const target of SKILL_TARGETS) {
    try {
      const skillDir = path.join(target, 'tract-workspace');
      fs.mkdirSync(skillDir, { recursive: true });
      fs.writeFileSync(path.join(skillDir, 'SKILL.md'), skillMd);
      fs.writeFileSync(path.join(skillDir, 'workspace.md'), workspaceMd);
    } catch { /* non-fatal */ }
  }
}

function isGitRepo(dir) {
  try {
    execSync('git rev-parse --git-dir', { cwd: dir, stdio: 'ignore' });
    return true;
  } catch { return false; }
}

function pullRepo(dir, label) {
  const prefix = `  ${chalk.cyan('↓')} ${label.padEnd(20)} `;

  // Announce before starting — large repos take time and silence looks like a hang
  process.stdout.write(prefix + chalk.gray('fetching...\n'));

  // Fetch latest (keep shallow with --depth=1)
  const fetch = spawnSync('git', ['fetch', '--depth=1', '--progress'], {
    cwd: dir,
    stdio: ['ignore', 'ignore', 'inherit'],  // stderr → terminal (git progress)
  });

  if (fetch.status !== 0) {
    console.log(`  ${chalk.red('✗')} ${label.padEnd(20)} ${chalk.red('fetch failed')}`);
    return false;
  }

  // Check if we're already up to date before resetting
  const localHead  = spawnSync('git', ['rev-parse', 'HEAD'],       { cwd: dir, encoding: 'utf8' }).stdout.trim();
  const fetchHead  = spawnSync('git', ['rev-parse', 'FETCH_HEAD'], { cwd: dir, encoding: 'utf8' }).stdout.trim();

  if (localHead === fetchHead) {
    console.log(`  ${chalk.cyan('✓')} ${label.padEnd(20)} ${chalk.gray('up to date')}`);
    return true;
  }

  // Hard reset to fetched tip — safe for read-only ticket mirrors
  const reset = spawnSync('git', ['reset', '--hard', 'FETCH_HEAD'], {
    cwd: dir,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  const out = (reset.stdout || '').trim();
  if (reset.status !== 0) {
    const msg = (reset.stderr || out || 'reset failed').trim().split('\n')[0];
    console.log(`  ${chalk.red('✗')} ${label.padEnd(20)} ${chalk.red(msg)}`);
    return false;
  }

  console.log(`  ${chalk.cyan('✓')} ${label.padEnd(20)} ${chalk.green('updated')}`);
  return true;
}

module.exports = function pull(options) {
  console.log(chalk.bold.cyan('\n▐ tract pull\n'));

  linkSkills();

  const repos = fs.existsSync(TRACT_DIR)
    ? fs.readdirSync(TRACT_DIR)
        .filter(name => !name.startsWith('.'))
        .map(name => ({ name, dir: path.join(TRACT_DIR, name) }))
        .filter(({ dir }) => {
          try { return fs.statSync(dir).isDirectory() && isGitRepo(dir); }
          catch { return false; }
        })
    : [];

  writeWorkspaceSkill(repos);

  if (repos.length === 0) {
    console.log(chalk.yellow('  No git repos found in ~/.tract/'));
    console.log(chalk.gray(`  Use 'tract clone <git-url>' or 'git clone <url> ~/.tract/<NAME>'\n`));
    process.exit(0);
  }

  let ok = 0, fail = 0;
  for (const { name, dir } of repos) {
    if (pullRepo(dir, name)) ok++; else fail++;
  }

  console.log('');
  if (fail === 0) {
    console.log(chalk.green(`  ✓ ${ok} repo(s) up to date\n`));
  } else {
    console.log(chalk.yellow(`  ${ok} updated, ${fail} failed\n`));
    process.exit(1);
  }
};
